# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "calendars", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "color", :string
    t.column "ical_url", :string
    t.column "group", :string
    t.column "slug", :string
  end

  create_table "events", :force => true do |t|
    t.column "start_date", :datetime
    t.column "end_date", :datetime
    t.column "title", :string
    t.column "description", :text
    t.column "content_id", :integer
    t.column "report_content_id", :integer
    t.column "location", :string
    t.column "approved", :boolean
    t.column "calendar_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "remember_token", :string
    t.column "remember_token_expires_at", :datetime
  end

end
